# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: NCPI-FHIR-Study-Summary-IG
canonical: https://ncpi-fhir.github.io/ncpi-fhir-study-summary-ig
name: NCPI FHIR Study Summary IG
title: NCPI FHIR Study Summary IG
description: "FHIR Implementation Guide for NCPI Study Summary Metadata"
status: draft
license: CC0-1.0
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: NCPI FHIR Working Group
  url: https://github.com/include-dcc
contact:
  - name: Eric Torstenson
    telecom:
      - system: email
        value: eric.s.torstenson@vumc.org
        use: work
dependencies:
  hl7.fhir.us.core: 3.1.1

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Background: 
    Data Dictionaries: data-dictionary.html
    Harmonization: harmonization.html
    Summary Data: summary_data.html
  Table of Contents: toc.html
  Artifacts: artifacts.html
  Support: 
    FHIR Spec: http://hl7.org/fhir/R4/index.html
    Downloads: downloads.html
